version: '3'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-nlw-devops
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
          - nlw
  networks:
    nlw:
      driver: bridge
