apiVersion: v1
kind: Deployment

metadata:
  name: nlw_devops-deployment
  label:
    app: nlw_devops

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nlw_devops
  template:
    metadata:
      labels:
        app: nlw_devops
    spec:
      containers:
        - name: nlw_devops
          image: diegorezm/nlw_devops:f80003b
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: url
          - name: API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: nlw-env
                key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi
