CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  sold bool DEFAULT false,
  entity_id INTEGER REFERENCES ProductEntity(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
