name: CI

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(eho $GITHUB_SHA| head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t diegorezm/nlw_devops:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push diegorezm/nlw_devops:${{ steps.generate_sha.outputs.sha }}
          docker tag diegorezm/nlw_devops:${{ steps.generate_sha.outputs.sha }} diegorezm/nlw_devops:latest
          docker push diegorezm/nlw_devops:latest
